name: Build and Deploy CompMax

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Explicitly grant write permission
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          
      - name: Replace API Keys and Service IDs
        run: |
          # Update the sed commands to match the placeholders in config.js
          sed -i "s/EMAILJS_PUBLIC_KEY/${{ secrets.EMAILJS_PUBLIC_KEY }}/g" js/config.js
          sed -i "s/EMAILJS_SERVICE_ID/${{ secrets.EMAILJS_SERVICE_ID }}/g" js/config.js
          sed -i "s/EMAILJS_TEMPLATE_ID/${{ secrets.EMAILJS_TEMPLATE_ID }}/g" js/config.js
          
          # Debug - show the replaced content (remove this in production)
          echo "Checking replacements..."
          grep -n "publicKey" js/config.js
          grep -n "serviceId" js/config.js
          grep -n "templateId" js/config.js
          
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: .  # The folder the action should deploy
          branch: gh-pages  # The branch the action should deploy to
