name: Build and Deploy CompMax

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          
      - name: Replace API Keys and Service IDs
        run: |
          # Fix: Use double quotes to allow variable expansion
          sed -i "s/\"EMAILJS_PUBLIC_KEY\"/\"${{ secrets.EMAILJS_PUBLIC_KEY }}\"/g" js/config.js
          sed -i "s/\"EMAILJS_SERVICE_ID\"/\"${{ secrets.EMAILJS_SERVICE_ID }}\"/g" js/config.js
          sed -i "s/\"EMAILJS_TEMPLATE_ID\"/\"${{ secrets.EMAILJS_TEMPLATE_ID }}\"/g" js/config.js
          
          # Show the result (masked)
          echo "After replacement:"
          grep -n "publicKey\|serviceId\|templateId" js/config.js
          
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: .
          branch: gh-pages
