name: Build and Deploy CompMax

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Explicitly grant write permission
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          
      - name: Replace API Keys and Service IDs
        run: |
          # Use proper quoting to ensure values are replaced correctly
          sed -i "s/EMAILJS_PUBLIC_KEY_PLACEHOLDER/${{ secrets.EMAILJS_PUBLIC_KEY }}/g" index.html
          sed -i "s/EMAILJS_SERVICE_ID_PLACEHOLDER/${{ secrets.EMAILJS_SERVICE_ID }}/g" index.html
          sed -i "s/EMAILJS_TEMPLATE_ID_PLACEHOLDER/${{ secrets.EMAILJS_TEMPLATE_ID }}/g" index.html
          
          # Debug - show the replaced content (remove this in production)
          echo "Checking replacements..."
          grep -n "emailjs.init" index.html
          grep -n "EMAILJS_SERVICE_ID" index.html
          grep -n "EMAILJS_TEMPLATE_ID" index.html
          
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: .  # The folder the action should deploy
          branch: gh-pages  # The branch the action should deploy to
